version: '3.8'

services:
  javalin-app:
    build: .
    ports:
      - "7070:7070"
    environment:
      - MONGO_URL=mongodb+srv://agtr0002_db_user:BW2gyZZiFwcJELug@appencuesta.jycbqks.mongodb.net/?appName=AppEncuesta
      - JWT_SECRET=SecretoSuperSeguroParaElProyectoFinal
      - PUERTO=7070
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
